会場をインプレスに変更 O123で実施
tattake/ichiyasaGitSample pull request #1
Opened 2021-04-25 11:27 UTC by tattake1234

O123でプルリクエストを処理した。20210425

2021-04-29 11:03 UTC, tattake commented
修正どうもでう！

2021-04-29 11:06 UTC, tattake commented
LGTM

2021-04-29 11:23 UTC, tattake requested changes
ちょっと確認お願いします

2021-04-29 11:23 UTC, tattake commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
他の会社名なかったのかな。

2021-04-29 11:23 UTC, tattake commented on index.html
>                          <h3>スピーカー</h3>
スピーカなのね。わかりました。

2021-04-29 11:30 UTC, tattake1234 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
この会社名でお願いします。 👍

2021-04-29 11:30 UTC, tattake1234 commented
👍

2021-04-29 11:45 UTC, tattake1234 reviewed
コメント書きました。よろ。

2021-04-29 11:45 UTC, tattake1234 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
かっこいい名前ないかん。

2021-04-29 11:45 UTC, tattake1234 commented on index.html
>                          <h3>スピーカー</h3>
はい、そうでがす。

2021-04-29 11:45 UTC, tattake1234 commented on index.html
>                      <article>
articleっていいと思いません？

2021-04-29 11:46 UTC, tattake commented on index.html
>                      <article>
いいね！

2021-04-29 11:48 UTC, tattake commented on index.html
>                          <h3>イベント日時・場所</h3>
イベントにちじとは？

2021-04-29 11:49 UTC, tattake1234 commented on index.html
>                          <h3>イベント日時・場所</h3>
場所もあります。

2021-04-29 11:51 UTC, tattake1234 commented on index.html
>                          <h3>イベント日時・場所</h3>
👍

2021-04-29 11:55 UTC, tattake1234 commented on index.html
>                          <h3>イベント日時・場所</h3>
どうでしょうか。

2021-04-29 11:56 UTC, tattake commented on index.html
>                          <h3>イベント日時・場所</h3>
いいかな。LGTM

2021-04-29 12:00 UTC, tattake1234 reviewed
よいですかねねねね。

2021-04-29 12:07 UTC, tattake commented on index.html
>                          <h3>イベント日時・場所</h3>
どうしようかな。。。。。。

2021-04-29 12:08 UTC, tattake1234 commented on index.html
>                          <h3>イベント日時・場所</h3>
どないすんですか。

2021-04-30 23:50 UTC, tattake approved these changes

2021-05-01 11:54 UTC, merged

2021-05-01 11:57 UTC, tattake1234 commented
あざーす

2021-05-01 11:57 UTC, tattake1234 commented
うん?

2021-05-01 11:58 UTC, tattake commented
　👍